
accelerate launch stage1_vae_trainer.py \
  --experiment_name "VAETrainer" \
  --wandb_run_name "vqvae_celebahq" \
  --working_directory "work_dir/vqvae_celebahq" \
  --log_wandb \
  --img_size 256 \
  --in_channels 3 \
  --out_channels 3 \
  --latent_channels 4 \
  --residual_layers_per_block 2 \
  --attention_layers 1 \
  --attention_residual_connections \
  --vae_channels_per_block 64 128 256 256 \
  --vae_up_down_factor 2 \
  --vae_up_down_kernel_size 3 \
  --quantize \
  --codebook_size 8192 \
  --vq_embed_dim 4 \
  --commitment_beta 0.25 \
  --pixelwise_average \
  --disc_start_dim 64 \
  --disc_depth 3 \
  --disc_kernel_size 4 \
  --disc_leaky_relu_slope 0.2 \
  --disc_learning_rate 4.5e-6 \
  --disc_lr_scheduler cosine \
  --disc_lr_warmup_steps 2000 \
  --disc_start 20000 \
  --disc_weight 0.5 \
  --disc_loss hinge \
  --use_lpips_package \
  --lpips_weight 0.5 \
  --learning_rate 4.5e-6 \
  --lr_scheduler cosine \
  --lr_warmup_steps 2000 \
  --total_train_iterations 50000 \
  --checkpoint_iterations 2500 \
  --per_gpu_batch_size 16 \
  --gradient_accumulation_steps 1 \
  --num_workers 32 \
  --max_grad_norm 1.0 \
  --dataset celebahq \
  --path_to_data "/mnt/datadrive/data/CelebAMask-HQ/CelebA-HQ-img/" \
  --pin_memory \
  --interpolation bilinear \
  --random_flip_p 0.0 \
  --reconstruction_loss_fn l1 \
  --scale_perceptual_by_var \
  --codebook_weight 0.000001 \
  --val_img_folder_path src/samples/celebahq \
  --val_image_gen_save_path src/celebahq_vqvae \
  --val_generation_freq 50 \
  --beta1 0.5 \
  --beta2 0.999 \
  --weight_decay 5e-3
