
accelerate launch stage1_vae_trainer.py \
  --experiment_name "VAETrainer" \
  --wandb_run_name "vae_celeba" \
  --working_directory "work_dir/vae_celeba" \
  --log_wandb \
  --img_size 128 \
  --in_channels 3 \
  --out_channels 3 \
  --latent_channels 4 \
  --residual_layers_per_block 1 \
  --attention_layers 1 \
  --attention_residual_connections \
  --vae_channels_per_block 128 256 256 512 \
  --vae_up_down_factor 2 \
  --vae_up_down_kernel_size 3 \
  --disc_start_dim 64 \
  --disc_depth 3 \
  --disc_kernel_size 4 \
  --disc_leaky_relu_slope 0.2 \
  --disc_learning_rate 4.5e-6 \
  --disc_lr_scheduler cosine \
  --disc_lr_warmup_steps 5000 \
  --disc_start 30001 \
  --disc_weight 0.5 \
  --disc_loss hinge \
  --use_lpips_package \
  --lpips_weight 0.5 \
  --learning_rate 4.5e-6 \
  --lr_scheduler cosine \
  --lr_warmup_steps 2500 \
  --total_train_iterations 100000 \
  --checkpoint_iterations 5000 \
  --per_gpu_batch_size 64 \
  --gradient_accumulation_steps 1 \
  --num_workers 32 \
  --max_grad_norm 1.0 \
  --dataset celeba \
  --path_to_data "/mnt/datadrive/data/CelebA/img_align_celeba/img_align_celeba/" \
  --pin_memory \
  --interpolation bilinear \
  --random_flip_p 0.0 \
  --reconstruction_loss_fn l1 \
  --scale_perceptual_by_var \
  --kl_weight 0.000001 \
  --val_img_folder_path src/celeba/raw \
  --val_image_gen_save_path src/celeba \
  --val_generation_freq 2500 \
  --beta1 0.5 \
  --beta2 0.9 \
  --weight_decay 5e-3 
